apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-default-deployment-binding
  namespace: default
subjects:
- kind: User
  name: john
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: edit-default-deployment
  apiGroup: rbac.authorization.k8s.io
